### ISSUE TITLE
include UTM code in get_distribution() output

### ISSUE THREAD

**Issue by AMBarbosa** [Pakillo/FloraIberica#2]
It would be useful if the output of `get_distribution()` included the "UTM.cell" column from the AFLIBER database , rather than just the centroid point coordinates. Cheers!

**Comment by Pakillo** [comment]
Thanks Marcia

I'll try and see how much that increases the dataset size (currently c. 2.5 MB, and should not become much larger as I intend to send this to CRAN...). If not increasing much, I can certainly include that

What would be the use case for UTM cells? I find geographical coordinates much easier and useful to work with?

**Comment by AMBarbosa** [comment]
Feel free to ignore if you think this would unnecessarily increase the data size! But if I understand correctly, these are not actually species observation points, but rather centroids of UTM grid cells where the observations were recorded. So, they should ideally be analyzed against data gathered or summarized over the same grid. For users who already have a table with environmental data on this UTM grid, having the "UTM.cell" ID would make the data join easier and probably less error-prone. But it's just a suggestion, do feel free to pass! :)

**Comment by Pakillo** [comment]
Thanks Marcia. That makes sense

I just checked, and including the UTM.cell in the dataset increases the size from 2.5 to 4 MB. Still within CRAN limits I think, but honestly unsure if it's worth it... (One of my goals with this package was actually to move away from UTM, which I find hard to work with :)

As far as I can see the main benefit of including that column would be for users already having **a table** of environmental data by UTM.cell (I wonder how common is that?). If they have environmental rasters in UTM projection they can of course reproject the point coordinates to UTM and extract the raster values. And if they have rasters in any other projection (which I thought would be the most common situation, e.g. lonlat rasters from Worldclim, or rasters in LAEA) they can choose a 10 km grid size to match that of AFLIBER. 

Anyway, if having UTM.cell can be useful to other people and it doesn't interfere with CRAN, I'm happy to include that as well

Any thoughts on this @iramosgutierrez ?

**Comment by iramosgutierrez** [comment]
I agree with Marcia, and she is correct, when we gathered the data we included the records occurring inside the polygon (and therefore re-converting them to points could potentially entail including erroneous information). Of course (as far as I see it), for visualization the centroid coordinates are sufficient, but for analyses I prefer using polygons, as I find them more accurate.
However, I presume re-converting centroids to polygons would not be very difficult in case you finally upload the package using coordinates for whatever reason.

**Comment by AMBarbosa** [comment]
I'm all in favour of moving away from UTM when we can, but as long as most of our species occurrence data come from that grid (i.e. the species occurred somewhere within the polygon of which the point is the centroid), we can't really move away from it without incurring in a bit of error. And it isn't straightforward to generate the UTM polygons from the centroid points because, at UTM zone unions, the grid cells are not regularly shaped (example [here](http://guiadigital.uam.es/SCUAM/documentacion/img/PI_Mallas_UTM.jpg)). For the same reason, it's not possible use a raster grid that matches the UTM grid across the Iberian Peninsula.

Again, feel free to consider that adding the "UTM.cell" codes is not an optimal use of package file size; but I do know of a few users who have tables of environmental data by UTM.cell, and in any case it should be clear that those point coordinates refer to the centroids of those cells, and not exact observation localities.

Cheers!

**Comment by Pakillo** [comment]
Alright! Many thanks for the discussion. I'll add the UTM.cell column to the dataset :)

I thought it was clear that the data are taken directly from the AFLIBER database with 10 km resolution, and should not be taken as point coordinates. I'll check the documentation to make that even more clear.

**Comment by Pakillo** [comment]
Done! Thanks for the feedback :)
